spring:
  application:
    name: discovery
server:
  port: 8082

eureka:
  instance:
    hostname: ${HOST:localhost}
  client:
    serviceUrl:
      defaultZone: http://${HOST:localhost}:8082/eureka/
    register-with-eureka: false
    fetch-registry: false