spring:
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost}:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: "search"
      properties:
        spring:
          json:
            trusted:
              packages: igor.film,igor.film.model,igor.film.model.Film
  elasticsearch:
    host: ${ELASTIC_URL:localhost}
    port: 9300
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: ${ELASTIC_URL:localhost}:9300
