spring:
  application:
    name: film-search
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost}:9092
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: "search"
      properties:
        spring:
          json:
            trusted:
              packages: igor.film,igor.film.model,igor.film.model.Film
  elasticsearch:
    host: ${ELASTIC_URL:localhost}
    port: 9300
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: ${ELASTIC_URL:localhost}:9300
server:
  port: 8083

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${DISCOVERY_URL:localhost}:8082/eureka/