spring:
  application:
    name: gateway
server:
  port:
    8080

eureka:
  client:
    region: default
  registryFetchIntervalSeconds: 5

zuul:
  routes:
    film-saver:
      path: /film-saver/**
      sensitive-headers: Set-Cookie,Authorization
    film-search:
      path: /film-search/**
      sensitive-headers: Set-Cookie,Authorization
    discovery:
      path: /discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://${DISCOVERY_URL:localhost}:8082

hystrix:
  command:
    film-saver:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    film-search:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000